name: video_player_cf
description: Flutter plugin for displaying inline video with other Flutter
  widgets on Android, iOS, and web.
repository: https://github.com/flutter/plugins/tree/master/packages/video_player/video_player
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+video_player%22
version: 2.2.10

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.videoplayercf
        pluginClass: VideoPlayerPlugin
      ios:
        pluginClass: CFLTVideoPlayerPlugin
      web:
        default_package: video_player_web

dependencies:
  video_player_platform_interface_cf: #^2.3.0
#    path: ../video_player_platform_interface
  # workaround for success build checks in PR
    git:
      ref: e1830f5cb4fb3aee289d88f5c48d04fe6fac94b7
      url: git@github.com:curefit/flutter-plugins.git
      path: packages/video_player/video_player_platform_interface
  # The design on https://flutter.dev/go/federated-plugins was to leave
  # this constraint as "any". We cannot do it right now as it fails pub publish
  # validation, so we set a ^ constraint.
  # TODO(amirh): Revisit this (either update this part in the  design or the pub tool).
  # https://github.com/flutter/flutter/issues/46264
  video_player_web_cf: #'>=0.1.5 <2.0.0'
#    path: ../video_player_web
    # workaround for success build checks in PR
    git:
      ref: f51bbd641cd36040e6000fcec269dd27fb152168
      url: git@github.com:curefit/flutter-plugins.git
      path: packages/video_player/video_player_web

  flutter:
    sdk: flutter
  meta: ^1.3.0
#  video_player_platform_interface: ">=4.2.0 <6.0.0"
#  video_player_web: ^2.0.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  pigeon: ^0.1.21
