// Autogenerated from Pigeon (v0.1.23), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class CFLTInitializeMessage;
@class CFLTTextureMessage;
@class CFLTCreateMessage;
@class CFLTLoopingMessage;
@class CFLTVolumeMessage;
@class CFLTPlaybackSpeedMessage;
@class CFLTPositionMessage;
@class CFLTMixWithOthersMessage;
@class CFLTDataSourceMessage;

@interface CFLTInitializeMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * maxCacheSize;
@property(nonatomic, strong, nullable) NSNumber * maxCacheFileSize;
@end

@interface CFLTTextureMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@end

@interface CFLTCreateMessage : NSObject
@property(nonatomic, copy, nullable) NSString * asset;
@property(nonatomic, copy, nullable) NSString * uri;
@property(nonatomic, copy, nullable) NSString * packageName;
@property(nonatomic, copy, nullable) NSString * formatHint;
@property(nonatomic, strong, nullable) NSNumber * useCache;
@property(nonatomic, strong, nullable) NSDictionary * httpHeaders;
@end

@interface CFLTLoopingMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * isLooping;
@end

@interface CFLTVolumeMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * volume;
@end

@interface CFLTPlaybackSpeedMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * speed;
@end

@interface CFLTPositionMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * textureId;
@property(nonatomic, strong, nullable) NSNumber * position;
@end

@interface CFLTMixWithOthersMessage : NSObject
@property(nonatomic, strong, nullable) NSNumber * mixWithOthers;
@end

@interface CFLTDataSourceMessage : NSObject
@property(nonatomic, copy, nullable) NSString * asset;
@property(nonatomic, copy, nullable) NSString * uri;
@property(nonatomic, copy, nullable) NSString * key;
@property(nonatomic, copy, nullable) NSString * packageName;
@property(nonatomic, copy, nullable) NSString * formatHint;
@property(nonatomic, strong, nullable) NSNumber * useCache;
@property(nonatomic, strong, nullable) NSNumber * textureId;

@end

@protocol CFLTVideoPlayerApi
-(void)initialize:(CFLTInitializeMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable CFLTTextureMessage *)create:(CFLTCreateMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)dispose:(CFLTTextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setLooping:(CFLTLoopingMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setVolume:(CFLTVolumeMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setPlaybackSpeed:(CFLTPlaybackSpeedMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)play:(CFLTTextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(nullable CFLTPositionMessage *)position:(CFLTTextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)seekTo:(CFLTPositionMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)pause:(CFLTTextureMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setMixWithOthers:(CFLTMixWithOthersMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
-(void)setDataSource:(CFLTDataSourceMessage*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void CFLTVideoPlayerApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<CFLTVideoPlayerApi> _Nullable api);

NS_ASSUME_NONNULL_END
